version: '3.8'
services:
  db:
    image: mysql:5.7
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  node:
    depends_on:
      - db
    build: 
      context: ./api
    restart: always
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
  ui:
    depends_on:
      - node
    build:
      context: ./client
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
volumes:
    db:
    
      